name=ArdRTOS
version=2.0.1
license=MIT
author=Alex Olson <sleepnow2@gmail.com>
maintainer=Alex Olson <sleepnow2@gmail.com>
sentence=ArdRTOS provides a simple cooperative operating system for embedded systems.
paragraph=ArdRTOS was designed from the ground up to be as simple as possible from the users perspective. This offers an easy on-ramp to learning what goes on behind an RTOS, and also offers a dead simple RTOS that will fit many hobbiests needs.
category=Device Control
url=https://github.com/sleepnow2/ArdRTOS
repository=https://github.com/sleepnow2/ArdRTOS
architectures=*
includes=ArdRTOS.h